services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AdrianBaez\ShortCode\DecoderCollection: ~

    AdrianBaez\ShortCode\Decoder\BracketDecoder: ~

    AdrianBaez\Bundle\ShortCodeBundle\Twig\ShortCodeExtension: ~

    AdrianBaez\Bundle\ShortCodeBundle\Twig\Runtime:
        tags:
            - { name: twig.runtime }
